### ISSUE TITLE
Replication stage 3 - listen tcp :6379: bind: address already in use

### ISSUE THREAD

**Issue by ketrabovsky** [codecrafters-io/build-your-own-redis#125]
I am getting following error
![obraz](https://github.com/codecrafters-io/build-your-own-redis/assets/27032173/189cc5d7-80ae-4fb9-89ca-b8abd7a29438)

This happens before my redis clone is even started so I am guessing it is problem on build-your-own-redis side

**Comment by rohitpaulk** [comment]
Okay! So here's the solution we've arrived at: 

- We'll remove all usages of `SO_REUSEPORT` across all starter code, and replace it with `SO_REUSEADDR` instead. This is  consistent with what the official Redis does. 

- We'll change the error message here (when **we** fail to bind to a port) to be more friendly. It can say "Failed to bind to port <PORT>. This usually happens if `SO_REUSEADDR` was not set when your program bound to this port previously."

**Comment by ketrabovsky** [comment]
Using `SO_REUSEADDR` solved issue. Thanks!
![obraz](https://github.com/codecrafters-io/build-your-own-redis/assets/27032173/7900c39f-2f73-4d02-babf-0a8403638841)
