### ISSUE TITLE
[streams] Blocking reads compare strictly

### ISSUE THREAD

**Issue by lipinskipawel** [codecrafters-io/build-your-own-redis#159]
Hello
I enjoy your website and implementing your challenges are fun :) 

However, I think I faced a small bug during streams stage at "Blocking reads" task.
The tester is comparing responses strictly instead of using some sort of `containsAll` assertion.
Is this intentional or I should fix my code?

![image](https://github.com/codecrafters-io/build-your-own-redis/assets/47224674/4724c1c2-6415-47ce-a58f-26c171d6ecaf)

**Comment by rohitpaulk** [comment]
Hey @lipinskipawel! Thanks for reporting this, it looks like the official Redis implementation does always return these in the same order as the stream keys in the command. 

I'll keep this open so that we can add a note to the instructions + we'll also see if there's an official note either in the Redis docs / source code about this behaviour that we can link to.
